name: CD Deployment

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed
    branches:
      - cicd-test

jobs:
  deploy:
    name: CD Deployment
    runs-on: self-hosted
    
    steps:
      - name: Update the packages 
        run: sudo apt update -y
      - name: Install nodejs and npm
        run: sudo apt install nodejs npm -y
      - name: list all the files and folder in build directory
        run: ls        
      - name: download the artifacts from build job
        uses: dawidd6/action-download-artifact@v3
        with: 
          name: nodejs-app-artifacts
          path: ./nodejs-app-artifacts
          workflow: ci.yml
          run_id: ${{ github.event.workflow_run.id }}
      - name: Deployment completed
        run: echo "Deployment completed successfully"
      # - name: start the node services
      #   run: |
      #     cd nodejs-app-artifacts
      #     npm install
      #     npm start
      # - name:  nohup node /home/ubuntu/actions-runner/_work/nodejs-app-nov-2025/nodejs-app-nov-2025/nodejs-app-artifacts/src/index.js &
      #   run: echo "Node services started successfully"